# Trip planner comparison evaluation configuration for comparing different prompt responses with multiple models
comparison:
  structured: false

  criteria:
    - type: comparison
      name: overall_quality
      question: |-
        Evaluate based on these criteria:
        1. Relevance to user preferences (themes, pace, budget, food style, dietary needs)
        2. Feasibility of the itinerary (realistic timing, logistics, proximity)
        3. Quality of recommendations (specific places, insider tips)
        4. Completeness of the plan (all days covered, restaurants, alternates)
      weight: 1.0